# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-30 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksInfo', '0001_initial'),
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='book_count', verbose_name='数量')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='booksInfo.Book')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='userInfo.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=50, verbose_name='订单号')),
                ('orderdetail', models.TextField(verbose_name='订单详情')),
                ('addressname', models.CharField(max_length=50, verbose_name='收件人')),
                ('addressphone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('orderaddress', models.CharField(max_length=100, verbose_name='收件人地址')),
                ('ordertime', models.DateField(auto_now=True)),
                ('orderacot', models.IntegerField(verbose_name='总数')),
                ('orderacount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价')),
                ('orderstatus', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '取消订单')], default=1, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userInfo.UserInfo')),
            ],
        ),
    ]
